### ISSUE TITLE
1 - [Feature] to save graph configuration in states || 2 - [bug] manage the reload after reconfiguration

### ISSUE THREAD

**Issue by secretresponder** [ElsaTam/obsidian-extended-graph#132]
[feature] hi! it would be perfect if configurations can be saved with states

---

[bug] also, i noticed that if i change the config graph dont change its view. 

the difference between configs is: i change the "properties" tab, replacing some of the nodes names with a frontmatter param.

and even if i reload the graph page it doesnt help. maybe reloading the cache or something like this will help?

**Comment by ElsaTam** [comment]
Hi!

Regarding the feature, I will work on it.

As for the bug, you're right, I was uncorrectly unloading/restoring some modifications before reloading the graph. It will be fixed in the next release :)

**Comment by ElsaTam** [comment]
I think I have fixed the bug in [2.6.2](https://github.com/ElsaTam/obsidian-extended-graph/releases/tag/2.6.2).

This release also has the feature you requested. Go in the "Automation" section and enable "Save configuration with state".

**Comment by secretresponder** [comment]
dunno, bug still exists

situation:

I have state 1 and state 2.

And cfg 1:

<img width="984" height="117" alt="Image" src="https://github.com/user-attachments/assets/340ab791-573d-4202-9960-013dfc0d3eca" />

 and cfg 2 with some properties:

<img width="978" height="127" alt="Image" src="https://github.com/user-attachments/assets/4b35dda5-0bbe-4600-872c-0adf6ab227e1" />

<img width="731" height="253" alt="Image" src="https://github.com/user-attachments/assets/8fcf52e5-1461-43e2-854f-8e1194b9b4a1" />

---

I've imported the cfg 2 and it had its effect - the nodes name changed to frontmatter values. But when i try to change to cfg1, I have no reaction - there's still frontmatter values.

**Comment by secretresponder** [comment]
well, it definitely has some bugs. i do press "save" in state 1 with its config. it saves the config, i can check the settings really changes depends on state. but it won't affect the rendering(

f.e. i have 2 states with different settings in links

<img width="949" height="101" alt="Image" src="https://github.com/user-attachments/assets/04900d72-a240-4e84-8d6c-7d89ac74d056" />

but when i change the states, links remain colored anyway

**Comment by ElsaTam** [comment]
It might be the fact that I fixed other things and it ended up fixing that too, but apparently I don't have the bug anymore 😄 Let's hope you won't have it neither.
I will push the Beta release probably tomorrow, but it will still be a beta for a few days more because I changed a lot of things and want to make sure I didn't break things that were fine.

https://github.com/user-attachments/assets/be6b1cd9-1f8a-4895-bbb0-c201079d52bf

**Comment by ElsaTam** [comment]
[2.6.5](https://github.com/ElsaTam/obsidian-extended-graph/releases/tag/2.6.5) is the latest public release containing this feature(s)
